server.port=8080

# Spring AI Anthropic (Claude) Configuration
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-sonnet-5-5

# Blockchain Node & Contract Configuration
blockchain.rpc-url=http://127.0.0.1:8545
blockchain.contract-address=0x5fbdb2315678afecb367f032d93f642f64180aa3
blockchain.wallet-private-key= 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80